export const characters = [
    {
        id: 0,
        name: "Tony Stark",
        img: "./src/assets/images/Characters/TonyStark.jpg",
        description: "Cool guy",
        baseLink: "/characters",
        comics: ["Comic about Tony Stark", "Some Comic"],
    },
    {
        id: 1,
        name: "many text many text many text many text many text many text many text many text many text",
        img: "",
        description: "many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text",
        baseLink: "/characters",
        comics: ["ni", "san"],
    },
    {
        id: 2,
        name: "Somebody",
        img: "",
        description: "",
        baseLink: "/characters",
        comics: ["Comic about Tony Stark", "Some Comic"],
    },
    {
        id: 3,
        name: "idk",
        img: "",
        description: "asd",
        baseLink: "/characters",
        comics: ["Comic about Tony Stark", "Some Comic"],
    },
    {
        id: 4,
        name: "one",
        img: "",
        description: "098",
        baseLink: "/characters",
        comics: ["Comic about Tony Stark", "Some Comic"],
    },
    {
        id: 5,
        name: "two",
        img: "./src/assets/images/Characters/TonyStark.jpg",
        description: "Cool guy",
        baseLink: "/characters",
        comics: ["Comic about Tony Stark", "Some Comic"],
    },
    {
        id: 6,
        name: "three",
        img: "",
        description: "345",
        baseLink: "/characters",
        comics: ["Comic about Tony Stark", "Some Comic"],
    },
    {
        id: 7,
        name: "four",
        img: "",
        description: "",
        baseLink: "/characters",
        comics: ["Comic about Tony Stark", "Some Comic"],
    },
    {
        id: 8,
        name: "five",
        img: "",
        description: "asd",
        baseLink: "/characters",
        comics: ["Comic about Tony Stark", "Some Comic"],
    },
    {
        id: 9,
        name: "six",
        img: "",
        description: "098",
        baseLink: "/characters",
        comics: ["Comic about Tony Stark", "Some Comic"],
    },
  ];