export const characters = [
    {
        id: 0,
        name: "Tony Stark",
        img: "./src/assets/images/Characters/TonyStark.jpg",
        description: "Cool guy",
        baseLink: "/characters",
    },
    {
        id: 1,
        name: "many text many text many text many text many text many text many text many text many text",
        img: "",
        description: "many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text many text",
        baseLink: "/characters",
    },
    {
        id: 2,
        name: "aszxc",
        img: "",
        description: "",
        baseLink: "/characters",
    },
    {
        id: 3,
        name: "qwe",
        img: "",
        description: "asd",
        baseLink: "/characters",
    },
    {
        id: 4,
        name: "zxc",
        img: "",
        description: "098",
        baseLink: "/characters",
    },
    {
        id: 5,
        name: "Tony Stark",
        img: "./src/assets/images/Characters/TonyStark.jpg",
        description: "Cool guy",
        baseLink: "/characters",
    },
    {
        id: 6,
        name: "123",
        img: "",
        description: "345",
        baseLink: "/characters",
    },
    {
        id: 7,
        name: "aszxc",
        img: "",
        description: "",
        baseLink: "/characters",
    },
    {
        id: 8,
        name: "qwe",
        img: "",
        description: "asd",
        baseLink: "/characters",
    },
    {
        id: 9,
        name: "zxc",
        img: "",
        description: "098",
        baseLink: "/characters",
    },
  ];