export const comics = [
    {
        id: 0,
        name: "Tony Stark",
        img: "../../assets/images/Characters/TonyStark.jpg",
        description: "Cool guy",
        baseLink: "/comics",
    },
    {
        id: 1,
        name: "123",
        img: "",
        description: "345",
        baseLink: "/comics",
    },
    {
        id: 2,
        name: "aszxc",
        img: "",
        description: "",
        baseLink: "/comics",
    },
    {
        id: 3,
        name: "qwe",
        img: "",
        description: "asd",
        baseLink: "/comics",
    },
    {
        id: 4,
        name: "zxc",
        img: "",
        description: "098",
        baseLink: "/comics",
    },
    {
        id: 5,
        name: "Tony Stark",
        img: "../../assets/images/Characters/TonyStark.jpg",
        description: "Cool guy",
        baseLink: "/comics",
    },
    {
        id: 6,
        name: "123",
        img: "",
        description: "345",
        baseLink: "/comics",
    },
    {
        id: 7,
        name: "aszxc",
        img: "",
        description: "",
        baseLink: "/comics",
    },
    {
        id: 8,
        name: "qwe",
        img: "",
        description: "asd",
        baseLink: "/comics",
    },
    {
        id: 9,
        name: "zxc",
        img: "",
        description: "098",
        baseLink: "/comics",
    },
  ];